Updated API client

diff --git a/redacteur b/redacteur
--- a/redacteur
+++ b/redacteur
@@ -2,60 +2,90 @@
 
 api_url="$JOURNALIST_API_URL"
 
-if ! type curl > /dev/null
-then
-  printf "curl missing, please install\n"
-  exit 1
-fi
-if ! type jq > /dev/null
-then
-  printf "jq missing, please install\n"
-  exit 1
-fi
+depcheck() {
+  dep="$1"
+  if ! type $dep > /dev/null
+  then
+    printf "$dep missing, please install\n"
+    exit 1
+  fi
+}
 
-if [ "$#" -lt 7 ]
-then
+usage() {
   printf "usage: %s perform <action> on <endpoint> as <username> <password> [with <payload>]\n" "$0"
   printf "\n"
   printf "action: get, post, put, delete\n"
   printf "endpoint: users[/<id>], tokens[/<id>], feeds[/<id>]\n"
   printf "payload: JSON string\n"
   printf "\n"
+  printf "environment:\n"
+  printf "\n"
+  printf "JOURNALIST_API_URL: url to Journalist's API endpoint, e.g. http://127.0.0.1:8000/api\n"
+  printf "\n"
   printf "examples:\n"
   printf "\n"
   printf "%s perform get on users/d83807a0-22ec-4c9f-94bf-fee5cf882d6e as admin \$(pass show journalist/admin)\n" "$0"
   printf "%s perform post on tokens as myuser mypassword with '{ \"name\": \"mytoken\" }'\n" "$0"
   printf "\n"
+}
+
+perform() {
+  if [ "$#" -lt 6 ]
+  then
+    usage
+    exit 1
+  fi
+
+  action=$(printf "%s" "$1" | tr '[:lower:]' '[:upper:]')
+  # "on"=$2
+  endpoint="$3"
+  # "as"=$4
+  user="$5"
+  pass="$6"
+  # "with"=$7
+  payload="$8"
+
+  if [ "$payload" = "" ]
+  then
+    json=$(curl -s -u "$user:$pass" -H 'Content-Type: application/json; charset=utf-8' -X "$action" "$api_url/$endpoint")
+  else
+    json=$(curl -s -u "$user:$pass" -H 'Content-Type: application/json; charset=utf-8' -X "$action" "$api_url/$endpoint" -d "$payload")
+  fi
+
+  if [ $? -ne 0 ]
+  then
+    printf "{}"
+    return 1
+  fi
+
+  printf "%s" "$json"
+  if printf "%s" "$json" | jq '.success' | grep "false" > /dev/null
+  then
+    return 2
+  fi
+
+  return 0
+}
+
+depcheck curl
+depcheck jq
+
+if [ "$#" -lt 1 ]
+then
+  usage
   exit 1
 fi
 
-# "perform"=$1
-action=$(printf "%s" "$2" | tr '[:lower:]' '[:upper:]')
-# "on"=$3
-endpoint="$4"
-# "as"=$5
-user="$6"
-pass="$7"
-# "with"=$8
-payload="$9"
+subcommand="$1"
 
-if [ "$payload" = "" ]
-then
-  json=$(curl -s -u "$user:$pass" -H 'Content-Type: application/json; charset=utf-8' -X "$action" "$api_url/$endpoint")
-else
-  json=$(curl -s -u "$user:$pass" -H 'Content-Type: application/json; charset=utf-8' -X "$action" "$api_url/$endpoint" -d "$payload")
-fi
+case "$subcommand" in
+  "perform")
+    perform "${@:2}"
+    exit $?
+    ;;
+  *)
+    usage
+    exit 1
+    ;;
+esac
 
-if [ $? -ne 0 ]
-then
-  printf "{}"
-  exit 1
-fi
-
-printf "%s" "$json"
-if printf "%s" "$json" | jq '.success' | grep "false" > /dev/null
-then
-  exit 2
-fi
-
-exit 0
